
name: Progress Bar CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Update README.md
      run: node index.js > README.md
    - name: Commit change & Push
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'linran754+github-actions[bot]@users.noreply.github.com'
          git commit -am "bot: update README.md automatically"
          git push


# GitHub Action for generating a contribution graph with a snake eating your contributions.name: Generate Snakeon:schedule:- cron: "0 0 * * *"workflow_dispatch:jobs:build:runs-on: ubuntu-lateststeps:- name: Checkoutuses: actions/checkout@v2.3.4- name: Generate Snakeuses: Platane/snk@masterid: snake-gifwith:github_user_name: ${{ github.repository_owner }}gif_out_path: ./assets/github-contribution-grid-snake.gifsvg_out_path: ./assets/github-contribution-grid-snake.svg- name: Push to GitHubuses: EndBug/add-and-commit@v7.2.1with:branch: mainmessage: 'Generate Contribution Snake'
